[variables]
NODE_VERSION = "20.19.0"
NODE_OPTIONS = "--max-old-space-size=4096"

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmd = "npx http-server ./dist/frontend -p $PORT -a 0.0.0.0"
