[build]
builder = "nixpacks"

[build.nixpacksConfig]
nodeVersion = "20.19.0"

[env]
NODE_VERSION = "20.19.0"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
