[build]
builder = "nixpacks"

[variables]
NODE_VERSION = "22"
NPM_CONFIG_ENGINE_STRICT = "false"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
