[build]
builder = "nixpacks"

[build.nixpacksConfig]
nodeVersion = "20.19.0"

[variables]
NODE_VERSION = "20.19.0"
NPM_CONFIG_ENGINE_STRICT = "false"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
